version: '2'
services:
    vm:
      privileged: true
      image: vm:latest
      build:
        context: ./
        dockerfile: Dockerfile
      environment:
        - HTTP_PASSWORD=secret
        - VNC_PASSWORD=secret
      ports:
        - 10000:10000
        - 5037:5037
      volumes:
        - avd:/root/.android/avd
        - system-images:/opt/android-sdk/system-images
        - platforms:/opt/android-sdk/platforms
volumes:
  avd:
  system-images:
  platforms:
